#ifndef DATAITEMCREATOR_H
#define DATAITEMCREATOR_H
// Factory for DataItems. Automatically generated by script Dictionary.sh
#include "TString.h"
#include "DataItem.h"
namespace ExampleFramework {
class DataItemFactory{
  friend class CentralStorage;
  DataItem* Create(TString name);
};
}
#endif
