// Factory for DataItems. Automatically generated by script Dictionary.sh
#include "DataItemFactory.h"
#include "DICaloCluster.h"
#include "DICaloJet.h"
#include "DICalorimeterHit.h"
#include "DIClusteredTrackerHit.h"
#include "DIElectron.h"
#include "DIEventNumber.h"
#include "DIRawHit.h"
#include "DIRunNumber.h"
#include "DITrackerHit.h"
#include "DITrack.h"
#include "DITrackStub.h"
#include "DIVertex.h"

using namespace ExampleFramework;

DataItem* DataItemFactory::Create(TString name){

     if (name == "DICaloCluster") return new DICaloCluster();
     if (name == "DICaloJet") return new DICaloJet();
     if (name == "DICalorimeterHit") return new DICalorimeterHit();
     if (name == "DIClusteredTrackerHit") return new DIClusteredTrackerHit();
     if (name == "DIElectron") return new DIElectron();
     if (name == "DIEventNumber") return new DIEventNumber();
     if (name == "DIRawHit") return new DIRawHit();
     if (name == "DIRunNumber") return new DIRunNumber();
     if (name == "DITrackerHit") return new DITrackerHit();
     if (name == "DITrack") return new DITrack();
     if (name == "DITrackStub") return new DITrackStub();
     if (name == "DIVertex") return new DIVertex();
   return 0;
}

