#!/bin/bash

# this script creates the Factory class for DataItems
FILENAMEH="DataItemFactory.h"
FILENAMECXX="DataItemFactory.cxx"
#create list of header files in which DATA classes are
HEADERFILES=`ls DI*.h`
# extract class names
CLASSLIST=`echo $HEADERFILES | sed "s/\.h//g"`
echo headerfile list is
echo $HEADERFILES
echo class list is
echo $CLASSLIST

# start header file
cat <<EOF > $FILENAMEH
#ifndef DATAITEMCREATOR_H
#define DATAITEMCREATOR_H
// Factory for DataItems. Automatically generated by script Dictionary.sh
#include "TString.h"
#include "DataItem.h"
namespace ExampleFramework {
class DataItemFactory{
  friend class CentralStorage;
  DataItem* Create(TString name);
};
}
#endif
EOF

cat <<EOF > $FILENAMECXX
// Factory for DataItems. Automatically generated by script Dictionary.sh
#include "DataItemFactory.h"
EOF
for i in $HEADERFILES; do 
    echo "#include \"$i\"" >> $FILENAMECXX
done
cat <<EOF >> $FILENAMECXX

using namespace ExampleFramework;

DataItem* DataItemFactory::Create(TString name){

EOF
for i in $CLASSLIST; do
    echo "     if (name == \"$i\") return new $i();" >> $FILENAMECXX
done
cat <<EOF >> $FILENAMECXX
   return 0;
}

EOF
